/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rtec.Telas;

/**
 *
 * @author ramsessf
 */
import Controller.ControllerTelaUsuario;
import java.sql.*;
import br.com.rtec.Dal.ModuloConexao;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class TelaUsuario extends javax.swing.JInternalFrame {
    
    // usando a variavel conexao do DAL
    Connection conexao = null;
    //Criando as variaves especiais para a conexao com o banco
    // Prepared Statement e ResultSet são frameworks do pacote java.sql
    //e servem para preparar e executar as instrucoes SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    private ControllerTelaUsuario controller;

    public TelaUsuario() {
        initComponents();
        controller = new ControllerTelaUsuario(this);
         
        //botao revelar senha
        /*
         if (txtUsuSenha.getText() == null) {
         btnRevSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/Icones/naorevelapwd.png")));
           

         } else {
         btnRevSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/Icones/revelapwd.png")));
           
         }*/
    }

    public JTextField getTxtUsuFone() {
        return txtUsuFone;
    }

    public void setTxtUsuFone(JTextField txtUsuFone) {
        this.txtUsuFone = txtUsuFone;
    }

    public JTextField getTxtUsuId() {
        return txtUsuId;
    }

    public void setTxtUsuId(JTextField txtUsuId) {
        this.txtUsuId = txtUsuId;
    }

    public JTextField getTxtUsuLogin() {
        return txtUsuLogin;
    }

    public void setTxtUsuLogin(JTextField txtUsuLogin) {
        this.txtUsuLogin = txtUsuLogin;
    }

    public JTextField getTxtUsuNome() {
        return txtUsuNome;
    }

    public void setTxtUsuNome(JTextField txtUsuNome) {
        this.txtUsuNome = txtUsuNome;
    }

    public JPasswordField getTxtUsuSenha() {
        return txtUsuSenha;
    }

    public void setTxtUsuSenha(JPasswordField txtUsuSenha) {
        this.txtUsuSenha = txtUsuSenha;
    }

    public JComboBox getCmbUsuPerfil() {
        return cmbUsuPerfil;
    }

    public void setCmbUsuPerfil(JComboBox cmbUsuPerfil) {
        this.cmbUsuPerfil = cmbUsuPerfil;
    }

    public JButton getBtnLimpar() {
        return btnLimpar;
    }

    public void setBtnLimpar(JButton btnLimpar) {
        this.btnLimpar = btnLimpar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }

    public JButton getBtnUsuAdd() {
        return btnUsuAdd;
    }

    public void setBtnUsuAdd(JButton btnUsuAdd) {
        this.btnUsuAdd = btnUsuAdd;
    }

    public JButton getBtnUsuAlterar() {
        return btnUsuAlterar;
    }

    public void setBtnUsuAlterar(JButton btnUsuAlterar) {
        this.btnUsuAlterar = btnUsuAlterar;
    }

    public JButton getBtnUsuConsul() {
        return btnUsuConsul;
    }

    public void setBtnUsuConsul(JButton btnUsuConsul) {
        this.btnUsuConsul = btnUsuConsul;
    }

    public JButton getBtnUsuDel() {
        return btnUsuDel;
    }

    public void setBtnUsuDel(JButton btnUsuDel) {
        this.btnUsuDel = btnUsuDel;
    }   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtUsuId = new javax.swing.JTextField();
        txtUsuNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUsuFone = new javax.swing.JTextField();
        lblConsPerfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbUsuPerfil = new javax.swing.JComboBox();
        txtUsuSenha = new javax.swing.JPasswordField();
        txtUsuLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUsuConsul = new javax.swing.JButton();
        btnUsuDel = new javax.swing.JButton();
        btnUsuAlterar = new javax.swing.JButton();
        btnUsuAdd = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Usuários");

        lblId.setText("*Id:");

        lblNome.setText("*Nome:");

        txtUsuId.setEnabled(false);
        txtUsuId.setPreferredSize(new java.awt.Dimension(0, 20));

        txtUsuNome.setEnabled(false);
        txtUsuNome.setPreferredSize(new java.awt.Dimension(0, 30));

        jLabel1.setText("Fone:");

        txtUsuFone.setEnabled(false);
        txtUsuFone.setPreferredSize(new java.awt.Dimension(0, 30));

        lblConsPerfil.setForeground(new java.awt.Color(255, 0, 0));
        lblConsPerfil.setEnabled(false);

        jLabel2.setText("* Campos Obrigatórios");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Definição de Acesso"));

        cmbUsuPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "user" }));
        cmbUsuPerfil.setEnabled(false);
        cmbUsuPerfil.setPreferredSize(new java.awt.Dimension(0, 30));
        cmbUsuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuPerfilActionPerformed(evt);
            }
        });

        txtUsuSenha.setEnabled(false);
        txtUsuSenha.setPreferredSize(new java.awt.Dimension(0, 30));
        txtUsuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuSenhaActionPerformed(evt);
            }
        });

        txtUsuLogin.setEnabled(false);
        txtUsuLogin.setPreferredSize(new java.awt.Dimension(0, 30));
        txtUsuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuLoginActionPerformed(evt);
            }
        });

        lblLogin.setText("*Login:");

        lblSenha.setText("*Senha:");

        jLabel3.setText("Perfil:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(154, 154, 154)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUsuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(cmbUsuPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtUsuSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbUsuPerfil, lblSenha, txtUsuLogin, txtUsuSenha});

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Dados Pessoais:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rtec/Icones/searchcpf.png"))); // NOI18N
        btnUsuConsul.setToolTipText("Consultar");
        btnUsuConsul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuConsul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuConsul.setPreferredSize(new java.awt.Dimension(70, 68));
        btnUsuConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuConsulActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, 70));

        btnUsuDel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ramsessf\\Desktop\\Curso Java aulaead\\icones_ferramentas\\icones\\iconfinder_delete-file_85306.png")); // NOI18N
        btnUsuDel.setToolTipText("Excluir");
        btnUsuDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuDel.setEnabled(false);
        btnUsuDel.setPreferredSize(new java.awt.Dimension(70, 68));
        btnUsuDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 12, 70, -1));

        btnUsuAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ramsessf\\Desktop\\Curso Java aulaead\\icones_ferramentas\\icones\\iconfinder_edit-file_85307.png")); // NOI18N
        btnUsuAlterar.setToolTipText("Alterar");
        btnUsuAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuAlterar.setEnabled(false);
        btnUsuAlterar.setPreferredSize(new java.awt.Dimension(70, 68));
        btnUsuAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 70));

        btnUsuAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUsuAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\ramsessf\\Desktop\\Curso Java aulaead\\icones_ferramentas\\icones\\iconfinder_new-file_85332.png")); // NOI18N
        btnUsuAdd.setToolTipText("Adicionar");
        btnUsuAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuAdd.setPreferredSize(new java.awt.Dimension(70, 68));
        btnUsuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rtec/Icones/save.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 70, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("      SALVAR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("     ADICIONAR");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("     EDITAR");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("   DELETAR");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("  PESQUISAR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("            CADASTRO DE USUÁRIO");

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rtec/Icones/iconfinder_eraser_70987.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("limpar os campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblConsPerfil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUsuId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(319, 319, 319))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsuFone, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuId, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtUsuNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuFone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar)
                    .addComponent(jLabel2))
                .addGap(154, 154, 154)
                .addComponent(lblConsPerfil)
                .addGap(309, 309, 309))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Dados para Acesso");

        setBounds(0, 0, 859, 673);
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void txtUsuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuLoginActionPerformed

    private void btnUsuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuAddActionPerformed
        //botao para limpar campos e adicionar um novo usuario
        controller.AdicionaNovosDadosDeUsuario();
        
    }//GEN-LAST:event_btnUsuAddActionPerformed

    private void cmbUsuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuPerfilActionPerformed

    private void btnUsuAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuAlterarActionPerformed
        controller.EditaDadosDeUsuario();
    }//GEN-LAST:event_btnUsuAlterarActionPerformed

    private void txtUsuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuSenhaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        //botao para limpar os campos
       controller.LimpaCamposDaTelaUsuario();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnUsuDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuDelActionPerformed
        controller.DeletaDadosDeUsuario();
    }//GEN-LAST:event_btnUsuDelActionPerformed

    private void btnUsuConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuConsulActionPerformed
        // chamada do método "consultar"
        controller.PesquisaDadosDeUsuario();
    }//GEN-LAST:event_btnUsuConsulActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //chama o metodo para gravar dados no banco
        controller.GravaDadosDeUsuario();
    }//GEN-LAST:event_btnSalvarActionPerformed

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUsuAdd;
    private javax.swing.JButton btnUsuAlterar;
    private javax.swing.JButton btnUsuConsul;
    private javax.swing.JButton btnUsuDel;
    private javax.swing.JComboBox cmbUsuPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblConsPerfil;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtUsuFone;
    protected javax.swing.JTextField txtUsuId;
    private javax.swing.JTextField txtUsuLogin;
    private javax.swing.JTextField txtUsuNome;
    private javax.swing.JPasswordField txtUsuSenha;
    // End of variables declaration//GEN-END:variables

}
